### ISSUE TITLE
Request for Training Pipeline to Rebuild Your Research 🌟

### ISSUE THREAD

**Issue by KaiCobra** [weichaozeng/TextCtrl#2]
Hi! I'm a student from Taiwan, and I recently discovered your research—it's absolutely fascinating! 😎

I'm really interested in learning more, and I'd love to rebuild your work to deepen my understanding. Would it be possible for you to share your training pipeline? It would be a huge help to me, and I'd greatly appreciate it!

Thank you so much for your time and effort! 🙏

Best regards,
Kai

**Comment by weichaozeng** [comment]
Thanks for your attention and sorry for the late reply. We've just updated the training pipeline. Feel free to try it out.
